# Generated by Django 4.0.4 on 2022-07-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
