env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "comma-dangle": "off",
  "quote-props": ["error", "consistent"],
  "object-curly-spacing": "off",
  "require-jsdoc": "off",
  "react/prop-types": "off",
  "max-len": [0, ]
  "react/no-unescaped-entities": [<enabled>, { "forbid": Array<string> }]
}