name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup ssh
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js Dependencies
      run: |
        cd intro
        npm install
        
    - name: Build React App
      run: |
        cd intro
        npm run-script build
        
    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main'
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: /home/portfolio/Portfolio
      run: |
        rsync -av -e "ssh -o StrictHostKeyChecking=no" --progress intro/build/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH/intro/static/intro/
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $DEPLOY_PATH &&
          git pull &&
          source /home/portfolio/venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          uwsgi --reload $DEPLOY_PATH/uwsgi.ini &&
          sudo service nginx reload
        "
